// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjGtfiK9eJAnqa33ssShEtb2seGkENsPA',
    appId: '1:873373620341:android:8fb3f80bf3eaf1353f803c',
    messagingSenderId: '873373620341',
    projectId: 'fir-e333d',
    databaseURL: 'https://fir-e333d.firebaseio.com',
    storageBucket: 'fir-e333d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwrY8dxkSBpGWtwlcfd8_y-t2NI8YyCJw',
    appId: '1:873373620341:ios:55cb1ad3f06235f23f803c',
    messagingSenderId: '873373620341',
    projectId: 'fir-e333d',
    databaseURL: 'https://fir-e333d.firebaseio.com',
    storageBucket: 'fir-e333d.appspot.com',
    androidClientId: '873373620341-aamfebe7ksqg0fqldtg0nervnbpk3emu.apps.googleusercontent.com',
    iosBundleId: 'com.arpit.speedometer',
  );
}
